package floors

type FloorsConfig map[string]SiteConfig

type SiteConfig struct {
	siteID    string
	siteUID   string
	platforms []string
	countries []string
}

var floorsConfig = FloorsConfig{
	"ViXOj3": SiteConfig{
		siteID:  "1992",
		siteUID: "ViXOj3",
		platforms: []string{
			"m-android/chrome",
			"m-ios/chrome",
			"t-android/chrome",
			"t-ios/chrome",
			"w/chrome",
			"m-android/edge",
			"t-android/edge",
			"t-ios/edge",
			"w/edge",
			"m-ios/google search",
			"t-ios/google search",
			"t-ios/safari",
			"m-ios/safari",
			"w/safari"},
		countries: []string{"US"},
	},
	"edj91d": SiteConfig{
		siteID:  "1991",
		siteUID: "edj91d",
		platforms: []string{
			"m-android/chrome",
			"m-ios/chrome",
			"t-android/chrome",
			"t-ios/chrome",
			"w/chrome",
			"m-android/edge",
			"t-android/edge",
			"t-ios/edge",
			"w/edge",
			"m-ios/google search",
			"t-ios/google search",
			"t-ios/safari",
			"m-ios/safari",
			"w/safari",
		},
	},
	"cXqfJb": SiteConfig{
		siteID:  "1989",
		siteUID: "cXqfJb",
		platforms: []string{
			"m-android/chrome",
			"m-ios/chrome",
			"t-android/chrome",
			"t-ios/chrome",
			"w/chrome",
			"m-android/edge",
			"t-android/edge",
			"t-ios/edge",
			"w/edge",
			"m-ios/google search",
			"t-ios/google search",
			"t-ios/safari",
			"m-ios/safari",
			"w/safari",
		},
	},
	"F2fUs0": SiteConfig{
		siteID:  "1994",
		siteUID: "F2fUs0",
		platforms: []string{
			"m-android/chrome",
			"m-ios/chrome",
			"t-android/chrome",
			"t-ios/chrome",
			"w/chrome",
			"m-android/edge",
			"t-android/edge",
			"t-ios/edge",
			"w/edge",
			"m-ios/google search",
			"t-ios/google search",
			"t-ios/safari",
			"m-ios/safari",
			"w/safari",
		},
	}, "CJ2Hu6": SiteConfig{
		siteID:  "1993",
		siteUID: "CJ2Hu6",
		platforms: []string{
			"m-android/chrome",
			"m-ios/chrome",
			"t-android/chrome",
			"t-ios/chrome",
			"w/chrome",
			"m-android/edge",
			"t-android/edge",
			"t-ios/edge",
			"w/edge",
			"m-ios/google search",
			"t-ios/google search",
			"t-ios/safari",
			"m-ios/safari",
			"w/safari",
		},
	}, "MtTEMQ": SiteConfig{
		siteID:  "1990",
		siteUID: "MtTEMQ",
		platforms: []string{
			"m-android/chrome",
			"m-ios/chrome",
			"t-android/chrome",
			"t-ios/chrome",
			"w/chrome",
			"m-android/edge",
			"t-android/edge",
			"t-ios/edge",
			"w/edge",
			"m-ios/google search",
			"t-ios/google search",
			"t-ios/safari",
			"m-ios/safari",
			"w/safari",
		},
	},
}
