package openrtb_ext

import (
	"testing"

	"github.com/prebid/openrtb/v19/openrtb2"
	"github.com/stretchr/testify/assert"
)

func TestSeatNonBidsAdd(t *testing.T) {
	type fields struct {
		seatNonBidsMap map[string][]NonBid
	}
	type args struct {
		nonBidParam NonBidParams
	}
	tests := []struct {
		name   string
		fields fields
		args   args
		want   map[string][]NonBid
	}{
		{
			name:   "nil-seatNonBidsMap",
			fields: fields{seatNonBidsMap: nil},
			args:   args{},
			want:   nil,
		},
		{
			name:   "nil-seatNonBidsMap-with-bid-object",
			fields: fields{seatNonBidsMap: nil},
			args:   args{nonBidParam: NonBidParams{Bid: &openrtb2.Bid{}, Seat: "bidder1"}},
			want:   sampleSeatNonBidMap("bidder1", 1),
		},
		{
			name:   "multiple-nonbids-for-same-seat",
			fields: fields{seatNonBidsMap: sampleSeatNonBidMap("bidder2", 1)},
			args:   args{nonBidParam: NonBidParams{Bid: &openrtb2.Bid{}, Seat: "bidder2"}},
			want:   sampleSeatNonBidMap("bidder2", 2),
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			snb := &NonBidsWrapper{
				seatNonBidsMap: tt.fields.seatNonBidsMap,
			}
			snb.AddBid(tt.args.nonBidParam)
			assert.Equalf(t, tt.want, snb.seatNonBidsMap, "expected seatNonBidsMap not nil")
		})
	}
}

func TestSeatNonBidsGet(t *testing.T) {
	type fields struct {
		snb *NonBidsWrapper
	}
	tests := []struct {
		name   string
		fields fields
		want   []SeatNonBid
	}{
		{
			name:   "get-seat-nonbids",
			fields: fields{&NonBidsWrapper{sampleSeatNonBidMap("bidder1", 2)}},
			want:   sampleSeatBids("bidder1", 2),
		},
		{
			name:   "nil-seat-nonbids",
			fields: fields{nil},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.fields.snb.Get(); !assert.Equal(t, tt.want, got) {
				t.Errorf("seatNonBids.get() = %v, want %v", got, tt.want)
			}
		})
	}
}

var sampleSeatNonBidMap = func(seat string, nonBidCount int) map[string][]NonBid {
	nonBids := make([]NonBid, 0)
	for i := 0; i < nonBidCount; i++ {
		nonBids = append(nonBids, NonBid{
			Ext: NonBidExt{Prebid: ExtResponseNonBidPrebid{Bid: NonBidObject{}}},
		})
	}
	return map[string][]NonBid{
		seat: nonBids,
	}
}

var sampleSeatBids = func(seat string, nonBidCount int) []SeatNonBid {
	seatNonBids := make([]SeatNonBid, 0)
	seatNonBid := SeatNonBid{
		Seat:   seat,
		NonBid: make([]NonBid, 0),
	}
	for i := 0; i < nonBidCount; i++ {
		seatNonBid.NonBid = append(seatNonBid.NonBid, NonBid{
			Ext: NonBidExt{Prebid: ExtResponseNonBidPrebid{Bid: NonBidObject{}}},
		})
	}
	seatNonBids = append(seatNonBids, seatNonBid)
	return seatNonBids
}

func TestSeatNonBidsMerge(t *testing.T) {
	type target struct {
		snb *NonBidsWrapper
	}
	tests := []struct {
		name   string
		fields target
		input  NonBidsWrapper
		want   *NonBidsWrapper
	}{
		{
			name:   "target-NonBidsWrapper-is-nil",
			fields: target{nil},
			want:   nil,
		},
		{
			name:   "input-NonBidsWrapper-contains-nil-map",
			fields: target{&NonBidsWrapper{}},
			input:  NonBidsWrapper{seatNonBidsMap: nil},
			want:   &NonBidsWrapper{},
		},
		{
			name:   "input-NonBidsWrapper-contains-empty-nonBids",
			fields: target{&NonBidsWrapper{}},
			input:  NonBidsWrapper{seatNonBidsMap: make(map[string][]NonBid)},
			want:   &NonBidsWrapper{},
		},
		{
			name:   "append-nonbids-in-empty-target-NonBidsWrapper",
			fields: target{&NonBidsWrapper{}},
			input: NonBidsWrapper{
				seatNonBidsMap: sampleSeatNonBidMap("pubmatic", 1),
			},
			want: &NonBidsWrapper{
				seatNonBidsMap: sampleSeatNonBidMap("pubmatic", 1),
			},
		},
		{
			name: "merge-multiple-nonbids-in-non-empty-target-NonBidsWrapper",
			fields: target{&NonBidsWrapper{
				seatNonBidsMap: sampleSeatNonBidMap("pubmatic", 1),
			}},
			input: NonBidsWrapper{
				seatNonBidsMap: sampleSeatNonBidMap("pubmatic", 1),
			},
			want: &NonBidsWrapper{
				seatNonBidsMap: sampleSeatNonBidMap("pubmatic", 2),
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.fields.snb.Append(tt.input)
			assert.Equal(t, tt.want, tt.fields.snb, "incorrect NonBidsWrapper generated by Append")
		})
	}
}
