# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"
  version = "1.3.0"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/coocood/freecache"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/erikstmartin/go-testdb"

[[constraint]]
  branch = "master"
  name = "github.com/evanphx/json-patch"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "~1.1.0"

[[constraint]]
  name = "github.com/mxmCherry/openrtb"
  version = "~9.2.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/vrischmann/go-metrics-influxdb"

[[constraint]]
  name = "github.com/yudai/gojsondiff"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
