apiVersion: v1
kind: Namespace
metadata:
  name: prebid
---
apiVersion: v1
kind: Service
metadata:
  namespace: prebid
  name: prebid-server
  labels:
    app: prebid
    role: server
    env: prod
spec:
  ports:
    - name: http
      port: 8000
    - name: metrics
      port: 9090
  selector:
    app: prebid
    role: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prebid
  name: prebid-server
  labels:
    app: prebid
    role: server
    env: prod
spec:
  selector:
    matchLabels:
      app: prebid
      role: server
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  template:
    metadata:
      labels:
        app: prebid
        role: server
    spec:
      containers:
        - name: server
          image: us.gcr.io/custom-citadel-106116/prebid-server:___VERSION___
          env:
            - { name: NODE_NAME,                  valueFrom: { fieldRef: { fieldPath: spec.nodeName } } }
            - { name: POD_NAMESPACE,              valueFrom: { fieldRef: { fieldPath: metadata.namespace } } }
            - { name: POD_ID,                     valueFrom: { fieldRef: { apiVersion: v1, fieldPath: metadata.uid } } }
            - { name: POD_NAME,                   valueFrom: { fieldRef: { fieldPath: metadata.name } } }
            - { name: POD_IP,                     valueFrom: { fieldRef: { fieldPath: status.podIP } } }
            - { name: HOST_IP,                    valueFrom: { fieldRef: { fieldPath: status.hostIP } } }
            - { name: PBS_EXTERNAL_URL,  value: "https://prebid.gamoshi.io" }
            - { name: PBS_HOST_COOKIE_DOMAIN,  value: ".gamoshi.io"}
            - { name: PBS_CACHE_SCHEME, value: "http" }
            - { name: PBS_CACHE_HOST, value: "prebid-cache.prebid.svc.cluster.local:2424" }
            - { name: PBS_CACHE_QUERY, value: "uuid=%PBS_CACHE_UUID%" }
            - { name: PBS_GDPR_USERSYNC_IF_AMBIGUOUS, value: "true" }
            - { name: PBS_GDPR_HOST_VENDR_ID, value: "644" }
            - { name: PBS_GDPR_ENABLED, value: "true" }
            - { name: PBS_GDPR_TIMEOUTS_MS_INIT_VENDORLIST_FETCHES, value: "60000" }
            - { name: PBS_GDPR_TIMEOUTS_MS_ACTIVE_VENDORLIST_FETCH, value: "60000" }
            - { name: PBS_PORT,  value: "8000" }
            - { name: PBS_STORED_REQUESTS_IN_MEMORY_CACHE_TYPE, value: "unbounded" }
            - { name: PBS_PDS_ADAPTERS_GAMOSHI_ENDPOINT, value: "http://gservice-prod" }
            - { name: PBS_METRICS_PROMETHEUS_PORT, value: "9090" }
            - { name: PBS_METRICS_PROMETHEUS_NAMESPACE, value: "prebid" }
            - { name: PBS_METRICS_PROMETHEUS_SUBSYSTEM, value: "server" }
            - { name: PBS_METRICS_PROMETHEUS_TIMEOUT_MS, value: "30000" }
            - { name: PBS_BLACKLISTED_ACCTS, value: "gamoshi-5977" }
          livenessProbe:
            failureThreshold: 3
            httpGet:
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 5
          ports:
            - { containerPort: 8000,    name: http }
            - { containerPort: 9090,    name: metrics }
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests: { cpu: 1.5, memory: 100Mi }
            limits:   { cpu: 1.5, memory: 500Mi }
      nodeSelector:
        cloud.google.com/gke-nodepool: prebid-preemptibles-2cpu-4gb
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  namespace: prebid
  name: server
  labels:
    app: prebid
    role: server
    env: prod
spec:
  maxReplicas: 15
  minReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: prebid-server
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prebid
  name: prebid-server
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
    - prebid
  selector:
    matchLabels:
      app: prebid
      role: server
---
