apiVersion: v1
kind: Namespace
metadata:
  name: prebid
---
apiVersion: v1
kind: Service
metadata:
  namespace: prebid
  name: prebid-server
  labels:
    app: prebid
    role: server
spec:
  ports:
    - name: http
      port: 8000
  selector:
    app: prebid
    role: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prebid
  name: prebid-server
  labels:
    app: prebid
    role: server
spec:
  selector:
    matchLabels:
      app: prebid
      role: server
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  template:
    metadata:
      labels:
        app: prebid
        role: server
    spec:
      containers:
        - name: server
          image: us.gcr.io/custom-citadel-106116/prebid-server:__VERSION__
          env:
            - { name: NODE_NAME,                  valueFrom: { fieldRef: { fieldPath: spec.nodeName } } }
            - { name: POD_NAMESPACE,              valueFrom: { fieldRef: { fieldPath: metadata.namespace } } }
            - { name: POD_ID,                     valueFrom: { fieldRef: { apiVersion: v1, fieldPath: metadata.uid } } }
            - { name: POD_NAME,                   valueFrom: { fieldRef: { fieldPath: metadata.name } } }
            - { name: POD_IP,                     valueFrom: { fieldRef: { fieldPath: status.podIP } } }
            - { name: HOST_IP,                    valueFrom: { fieldRef: { fieldPath: status.hostIP } } }
          livenessProbe:
            failureThreshold: 3
            httpGet:
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 1
          ports:
            - { containerPort: 8000,    name: http }
          readinessProbe:
            failureThreshold: 3
            httpGet:
              port: 8000
            periodSeconds: 5
            timeoutSeconds: 1
          resources:
            requests: { cpu: 2, memory: 100Mi }
            limits:   { cpu: 2, memory: 500Mi }
      tolerations:
        - key: app
          operator: Equal
          value: gservice
          effect: NoExecute
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  namespace: prebid
  name: server
  labels:
    app: prebid
    role: server
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: prebid-server
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: prebid
  name: server
  labels:
    app: prebid
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - prebid.gamoshi.io
    secretName: prebid-gamoshi-io-auto-tls
  - hosts:
    - prebid.gambid.io
    secretName: prebid-gambid-io-auto-tls
  - hosts:
    - prebid.gsh.io
    secretName: prebid-gsh-io-auto-tls
  rules:
  - host: prebid.gamoshi.io
    http: { paths: [ { backend: { serviceName: prebid-server, servicePort: 8000 } } ] }
  - host: prebid.gambid.io
    http: { paths: [ { backend: { serviceName: prebid-server, servicePort: 8000 } } ] }
  - host: prebid.gsh.io
    http: { paths: [ { backend: { serviceName: prebid-server, servicePort: 8000 } } ] }
---
