#!/bin/bash -ex

cd "$( dirname "${BASH_SOURCE[0]}" )"

if [[ ! -e secrets-repo ]]; then
    git clone keybase://team/prebid.prod/secrets secrets-repo
else
    pushd secrets-repo
    git pull
    popd
fi

ln -sf secrets-repo/tfstate/terraform.tfstate terraform.tfstate
