// Code generated by MockGen. DO NOT EDIT.
// Source: ./analytics/pubxai/processor/processor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	utils "github.com/prebid/prebid-server/v2/analytics/pubxai/utils"
)

// MockProcessorService is a mock of ProcessorService interface.
type MockProcessorService struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorServiceMockRecorder
}

// MockProcessorServiceMockRecorder is the mock recorder for MockProcessorService.
type MockProcessorServiceMockRecorder struct {
	mock *MockProcessorService
}

// NewMockProcessorService creates a new mock instance.
func NewMockProcessorService(ctrl *gomock.Controller) *MockProcessorService {
	mock := &MockProcessorService{ctrl: ctrl}
	mock.recorder = &MockProcessorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessorService) EXPECT() *MockProcessorServiceMockRecorder {
	return m.recorder
}

// ProcessLogData mocks base method.
func (m *MockProcessorService) ProcessLogData(ao *utils.LogObject) (*utils.AuctionBids, []utils.WinningBid) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessLogData", ao)
	ret0, _ := ret[0].(*utils.AuctionBids)
	ret1, _ := ret[1].([]utils.WinningBid)
	return ret0, ret1
}

// ProcessLogData indicates an expected call of ProcessLogData.
func (mr *MockProcessorServiceMockRecorder) ProcessLogData(ao interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessLogData", reflect.TypeOf((*MockProcessorService)(nil).ProcessLogData), ao)
}

// processBidData mocks base method.
func (m *MockProcessorService) processBidData(bidResponses []map[string]interface{}, ao *utils.LogObject) (*utils.AuctionBids, []utils.WinningBid) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "processBidData", bidResponses, ao)
	ret0, _ := ret[0].(*utils.AuctionBids)
	ret1, _ := ret[1].([]utils.WinningBid)
	return ret0, ret1
}

// processBidData indicates an expected call of processBidData.
func (mr *MockProcessorServiceMockRecorder) processBidData(bidResponses, ao interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "processBidData", reflect.TypeOf((*MockProcessorService)(nil).processBidData), bidResponses, ao)
}
