// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	hookstage "github.com/prebid/prebid-server/v3/hooks/hookstage"
	mock "github.com/stretchr/testify/mock"
)

// AuctionResponse is an autogenerated mock type for the AuctionResponse type
type AuctionResponse struct {
	mock.Mock
}

// HandleAuctionResponseHook provides a mock function with given fields: _a0, _a1, _a2
func (_m *AuctionResponse) HandleAuctionResponseHook(_a0 context.Context, _a1 hookstage.ModuleInvocationContext, _a2 hookstage.AuctionResponsePayload) (hookstage.HookResult[hookstage.AuctionResponsePayload], error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for HandleAuctionResponseHook")
	}

	var r0 hookstage.HookResult[hookstage.AuctionResponsePayload]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, hookstage.ModuleInvocationContext, hookstage.AuctionResponsePayload) (hookstage.HookResult[hookstage.AuctionResponsePayload], error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, hookstage.ModuleInvocationContext, hookstage.AuctionResponsePayload) hookstage.HookResult[hookstage.AuctionResponsePayload]); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(hookstage.HookResult[hookstage.AuctionResponsePayload])
	}

	if rf, ok := ret.Get(1).(func(context.Context, hookstage.ModuleInvocationContext, hookstage.AuctionResponsePayload) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuctionResponse creates a new instance of AuctionResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuctionResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuctionResponse {
	mock := &AuctionResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
