// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	hookstage "github.com/prebid/prebid-server/v3/hooks/hookstage"
	mock "github.com/stretchr/testify/mock"
)

// RawAuctionRequest is an autogenerated mock type for the RawAuctionRequest type
type RawAuctionRequest struct {
	mock.Mock
}

// HandleRawAuctionHook provides a mock function with given fields: _a0, _a1, _a2
func (_m *RawAuctionRequest) HandleRawAuctionHook(_a0 context.Context, _a1 hookstage.ModuleInvocationContext, _a2 hookstage.RawAuctionRequestPayload) (hookstage.HookResult[hookstage.RawAuctionRequestPayload], error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for HandleRawAuctionHook")
	}

	var r0 hookstage.HookResult[hookstage.RawAuctionRequestPayload]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, hookstage.ModuleInvocationContext, hookstage.RawAuctionRequestPayload) (hookstage.HookResult[hookstage.RawAuctionRequestPayload], error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, hookstage.ModuleInvocationContext, hookstage.RawAuctionRequestPayload) hookstage.HookResult[hookstage.RawAuctionRequestPayload]); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(hookstage.HookResult[hookstage.RawAuctionRequestPayload])
	}

	if rf, ok := ret.Get(1).(func(context.Context, hookstage.ModuleInvocationContext, hookstage.RawAuctionRequestPayload) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRawAuctionRequest creates a new instance of RawAuctionRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRawAuctionRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *RawAuctionRequest {
	mock := &RawAuctionRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
