// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	hookstage "github.com/prebid/prebid-server/v3/hooks/hookstage"
	mock "github.com/stretchr/testify/mock"
)

// RawBidderResponse is an autogenerated mock type for the RawBidderResponse type
type RawBidderResponse struct {
	mock.Mock
}

// HandleRawBidderResponseHook provides a mock function with given fields: _a0, _a1, _a2
func (_m *RawBidderResponse) HandleRawBidderResponseHook(_a0 context.Context, _a1 hookstage.ModuleInvocationContext, _a2 hookstage.RawBidderResponsePayload) (hookstage.HookResult[hookstage.RawBidderResponsePayload], error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for HandleRawBidderResponseHook")
	}

	var r0 hookstage.HookResult[hookstage.RawBidderResponsePayload]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, hookstage.ModuleInvocationContext, hookstage.RawBidderResponsePayload) (hookstage.HookResult[hookstage.RawBidderResponsePayload], error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, hookstage.ModuleInvocationContext, hookstage.RawBidderResponsePayload) hookstage.HookResult[hookstage.RawBidderResponsePayload]); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(hookstage.HookResult[hookstage.RawBidderResponsePayload])
	}

	if rf, ok := ret.Get(1).(func(context.Context, hookstage.ModuleInvocationContext, hookstage.RawBidderResponsePayload) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRawBidderResponse creates a new instance of RawBidderResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRawBidderResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *RawBidderResponse {
	mock := &RawBidderResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
