// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prebidNewsIQ.proto

package newsiq

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogPrebidEvents struct {
	Timestamp            uint64     `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RemoteAddrMacro      string     `protobuf:"bytes,2,opt,name=remote_addr_macro,json=remoteAddrMacro,proto3" json:"remote_addr_macro,omitempty"`
	UserAgentMacro       string     `protobuf:"bytes,3,opt,name=user_agent_macro,json=userAgentMacro,proto3" json:"user_agent_macro,omitempty"`
	RefererUrl           string     `protobuf:"bytes,4,opt,name=referer_url,json=refererUrl,proto3" json:"referer_url,omitempty"`
	SellerMemberId       uint32     `protobuf:"varint,5,opt,name=seller_member_id,json=sellerMemberId,proto3" json:"seller_member_id,omitempty"`
	Domain               string     `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	Device               string     `protobuf:"bytes,7,opt,name=device,proto3" json:"device,omitempty"`
	Auctions             []*Auction `protobuf:"bytes,8,rep,name=auctions,proto3" json:"auctions,omitempty"`
	NewsId               string     `protobuf:"bytes,9,opt,name=news_id,json=newsId,proto3" json:"news_id,omitempty"`
	Duid                 string     `protobuf:"bytes,10,opt,name=duid,proto3" json:"duid,omitempty"`
	Sid                  string     `protobuf:"bytes,11,opt,name=sid,proto3" json:"sid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LogPrebidEvents) Reset()         { *m = LogPrebidEvents{} }
func (m *LogPrebidEvents) String() string { return proto.CompactTextString(m) }
func (*LogPrebidEvents) ProtoMessage()    {}
func (*LogPrebidEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc48ebf32e61c541, []int{0}
}

func (m *LogPrebidEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogPrebidEvents.Unmarshal(m, b)
}
func (m *LogPrebidEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogPrebidEvents.Marshal(b, m, deterministic)
}
func (m *LogPrebidEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogPrebidEvents.Merge(m, src)
}
func (m *LogPrebidEvents) XXX_Size() int {
	return xxx_messageInfo_LogPrebidEvents.Size(m)
}
func (m *LogPrebidEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_LogPrebidEvents.DiscardUnknown(m)
}

var xxx_messageInfo_LogPrebidEvents proto.InternalMessageInfo

func (m *LogPrebidEvents) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LogPrebidEvents) GetRemoteAddrMacro() string {
	if m != nil {
		return m.RemoteAddrMacro
	}
	return ""
}

func (m *LogPrebidEvents) GetUserAgentMacro() string {
	if m != nil {
		return m.UserAgentMacro
	}
	return ""
}

func (m *LogPrebidEvents) GetRefererUrl() string {
	if m != nil {
		return m.RefererUrl
	}
	return ""
}

func (m *LogPrebidEvents) GetSellerMemberId() uint32 {
	if m != nil {
		return m.SellerMemberId
	}
	return 0
}

func (m *LogPrebidEvents) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *LogPrebidEvents) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *LogPrebidEvents) GetAuctions() []*Auction {
	if m != nil {
		return m.Auctions
	}
	return nil
}

func (m *LogPrebidEvents) GetNewsId() string {
	if m != nil {
		return m.NewsId
	}
	return ""
}

func (m *LogPrebidEvents) GetDuid() string {
	if m != nil {
		return m.Duid
	}
	return ""
}

func (m *LogPrebidEvents) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

type Auction struct {
	Version              string    `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	AuctionInitTimestamp uint64    `protobuf:"fixed64,2,opt,name=auction_init_timestamp,json=auctionInitTimestamp,proto3" json:"auction_init_timestamp,omitempty"`
	PrebidAuctionId      string    `protobuf:"bytes,3,opt,name=prebid_auction_id,json=prebidAuctionId,proto3" json:"prebid_auction_id,omitempty"`
	ConfiguredTimeoutMs  uint32    `protobuf:"varint,4,opt,name=configured_timeout_ms,json=configuredTimeoutMs,proto3" json:"configured_timeout_ms,omitempty"`
	AdUnits              []*AdUnit `protobuf:"bytes,5,rep,name=ad_units,json=adUnits,proto3" json:"ad_units,omitempty"`
	MsgType              uint32    `protobuf:"varint,6,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Auction) Reset()         { *m = Auction{} }
func (m *Auction) String() string { return proto.CompactTextString(m) }
func (*Auction) ProtoMessage()    {}
func (*Auction) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc48ebf32e61c541, []int{1}
}

func (m *Auction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auction.Unmarshal(m, b)
}
func (m *Auction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auction.Marshal(b, m, deterministic)
}
func (m *Auction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auction.Merge(m, src)
}
func (m *Auction) XXX_Size() int {
	return xxx_messageInfo_Auction.Size(m)
}
func (m *Auction) XXX_DiscardUnknown() {
	xxx_messageInfo_Auction.DiscardUnknown(m)
}

var xxx_messageInfo_Auction proto.InternalMessageInfo

func (m *Auction) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Auction) GetAuctionInitTimestamp() uint64 {
	if m != nil {
		return m.AuctionInitTimestamp
	}
	return 0
}

func (m *Auction) GetPrebidAuctionId() string {
	if m != nil {
		return m.PrebidAuctionId
	}
	return ""
}

func (m *Auction) GetConfiguredTimeoutMs() uint32 {
	if m != nil {
		return m.ConfiguredTimeoutMs
	}
	return 0
}

func (m *Auction) GetAdUnits() []*AdUnit {
	if m != nil {
		return m.AdUnits
	}
	return nil
}

func (m *Auction) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

type AdUnit struct {
	AdUnitCode           string   `protobuf:"bytes,1,opt,name=ad_unit_code,json=adUnitCode,proto3" json:"ad_unit_code,omitempty"`
	Bids                 []*Bid   `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Params               []*Param `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdUnit) Reset()         { *m = AdUnit{} }
func (m *AdUnit) String() string { return proto.CompactTextString(m) }
func (*AdUnit) ProtoMessage()    {}
func (*AdUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc48ebf32e61c541, []int{2}
}

func (m *AdUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdUnit.Unmarshal(m, b)
}
func (m *AdUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdUnit.Marshal(b, m, deterministic)
}
func (m *AdUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdUnit.Merge(m, src)
}
func (m *AdUnit) XXX_Size() int {
	return xxx_messageInfo_AdUnit.Size(m)
}
func (m *AdUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_AdUnit.DiscardUnknown(m)
}

var xxx_messageInfo_AdUnit proto.InternalMessageInfo

func (m *AdUnit) GetAdUnitCode() string {
	if m != nil {
		return m.AdUnitCode
	}
	return ""
}

func (m *AdUnit) GetBids() []*Bid {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *AdUnit) GetParams() []*Param {
	if m != nil {
		return m.Params
	}
	return nil
}

type Bid struct {
	BidId                string    `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	Price                float64   `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	BidderCode           string    `protobuf:"bytes,3,opt,name=bidder_code,json=bidderCode,proto3" json:"bidder_code,omitempty"`
	BidderAdUnitId       string    `protobuf:"bytes,4,opt,name=bidder_ad_unit_id,json=bidderAdUnitId,proto3" json:"bidder_ad_unit_id,omitempty"`
	RequestTimestamp     uint64    `protobuf:"fixed64,5,opt,name=request_timestamp,json=requestTimestamp,proto3" json:"request_timestamp,omitempty"`
	ResponseTimestamp    uint64    `protobuf:"fixed64,6,opt,name=response_timestamp,json=responseTimestamp,proto3" json:"response_timestamp,omitempty"`
	StatusCode           uint32    `protobuf:"varint,7,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Creative             *Creative `protobuf:"bytes,8,opt,name=creative,proto3" json:"creative,omitempty"`
	Source               string    `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Bid) Reset()         { *m = Bid{} }
func (m *Bid) String() string { return proto.CompactTextString(m) }
func (*Bid) ProtoMessage()    {}
func (*Bid) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc48ebf32e61c541, []int{3}
}

func (m *Bid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bid.Unmarshal(m, b)
}
func (m *Bid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bid.Marshal(b, m, deterministic)
}
func (m *Bid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bid.Merge(m, src)
}
func (m *Bid) XXX_Size() int {
	return xxx_messageInfo_Bid.Size(m)
}
func (m *Bid) XXX_DiscardUnknown() {
	xxx_messageInfo_Bid.DiscardUnknown(m)
}

var xxx_messageInfo_Bid proto.InternalMessageInfo

func (m *Bid) GetBidId() string {
	if m != nil {
		return m.BidId
	}
	return ""
}

func (m *Bid) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Bid) GetBidderCode() string {
	if m != nil {
		return m.BidderCode
	}
	return ""
}

func (m *Bid) GetBidderAdUnitId() string {
	if m != nil {
		return m.BidderAdUnitId
	}
	return ""
}

func (m *Bid) GetRequestTimestamp() uint64 {
	if m != nil {
		return m.RequestTimestamp
	}
	return 0
}

func (m *Bid) GetResponseTimestamp() uint64 {
	if m != nil {
		return m.ResponseTimestamp
	}
	return 0
}

func (m *Bid) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Bid) GetCreative() *Creative {
	if m != nil {
		return m.Creative
	}
	return nil
}

func (m *Bid) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type Creative struct {
	CreativeId           string   `protobuf:"bytes,1,opt,name=creative_id,json=creativeId,proto3" json:"creative_id,omitempty"`
	Width                uint32   `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Brand                string   `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Creative) Reset()         { *m = Creative{} }
func (m *Creative) String() string { return proto.CompactTextString(m) }
func (*Creative) ProtoMessage()    {}
func (*Creative) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc48ebf32e61c541, []int{4}
}

func (m *Creative) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Creative.Unmarshal(m, b)
}
func (m *Creative) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Creative.Marshal(b, m, deterministic)
}
func (m *Creative) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Creative.Merge(m, src)
}
func (m *Creative) XXX_Size() int {
	return xxx_messageInfo_Creative.Size(m)
}
func (m *Creative) XXX_DiscardUnknown() {
	xxx_messageInfo_Creative.DiscardUnknown(m)
}

var xxx_messageInfo_Creative proto.InternalMessageInfo

func (m *Creative) GetCreativeId() string {
	if m != nil {
		return m.CreativeId
	}
	return ""
}

func (m *Creative) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Creative) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Creative) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

type Param struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc48ebf32e61c541, []int{5}
}

func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (m *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(m, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Param) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*LogPrebidEvents)(nil), "LogPrebidEvents")
	proto.RegisterType((*Auction)(nil), "Auction")
	proto.RegisterType((*AdUnit)(nil), "AdUnit")
	proto.RegisterType((*Bid)(nil), "Bid")
	proto.RegisterType((*Creative)(nil), "Creative")
	proto.RegisterType((*Param)(nil), "Param")
}

func init() { proto.RegisterFile("prebidNewsIQ.proto", fileDescriptor_fc48ebf32e61c541) }

var fileDescriptor_fc48ebf32e61c541 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x54, 0xdb, 0x6e, 0xdb, 0x38,
	0x10, 0x85, 0x6f, 0x92, 0x3c, 0x5e, 0xe7, 0xc2, 0x4d, 0xb2, 0x5a, 0x60, 0xb1, 0x31, 0x8c, 0x16,
	0x70, 0x5b, 0xd4, 0x05, 0xd2, 0xfe, 0x80, 0x13, 0xf4, 0xc1, 0x40, 0x53, 0xa4, 0x42, 0xf2, 0x2c,
	0xc8, 0x9e, 0x89, 0x43, 0xd4, 0x12, 0x55, 0x92, 0x72, 0x90, 0x5f, 0xeb, 0xff, 0xf4, 0x1f, 0xfa,
	0x58, 0x70, 0x48, 0xc5, 0x79, 0x32, 0xcf, 0x85, 0x33, 0xf4, 0x19, 0x52, 0x20, 0x6a, 0x4d, 0x2b,
	0x89, 0x5f, 0xe9, 0xd1, 0x2c, 0xbf, 0xcd, 0x6b, 0xad, 0xac, 0x9a, 0xfe, 0xea, 0xc2, 0xe1, 0x17,
	0xb5, 0xb9, 0x61, 0xe5, 0xf3, 0x8e, 0x2a, 0x6b, 0xc4, 0x7f, 0x30, 0xb4, 0xb2, 0x24, 0x63, 0x8b,
	0xb2, 0x4e, 0x3b, 0x93, 0xce, 0x2c, 0xca, 0xf6, 0x84, 0x78, 0x0b, 0xc7, 0x9a, 0x4a, 0x65, 0x29,
	0x2f, 0x10, 0x75, 0x5e, 0x16, 0x6b, 0xad, 0xd2, 0xee, 0xa4, 0x33, 0x1b, 0x66, 0x87, 0x5e, 0x58,
	0x20, 0xea, 0x6b, 0x47, 0x8b, 0x19, 0x1c, 0x35, 0x86, 0x74, 0x5e, 0x6c, 0xa8, 0xb2, 0xc1, 0xda,
	0x63, 0xeb, 0x81, 0xe3, 0x17, 0x8e, 0xf6, 0xce, 0x73, 0x18, 0x69, 0xba, 0x27, 0x4d, 0x3a, 0x6f,
	0xf4, 0x36, 0xed, 0xb3, 0x09, 0x02, 0x75, 0xa7, 0xb7, 0xae, 0x94, 0xa1, 0xed, 0x96, 0x74, 0x5e,
	0x52, 0xb9, 0x22, 0x9d, 0x4b, 0x4c, 0x07, 0x93, 0xce, 0x6c, 0x9c, 0x1d, 0x78, 0xfe, 0x9a, 0xe9,
	0x25, 0x8a, 0x33, 0x88, 0x50, 0x95, 0x85, 0xac, 0xd2, 0x88, 0xab, 0x04, 0xc4, 0x3c, 0xed, 0xe4,
	0x9a, 0xd2, 0x38, 0xf0, 0x8c, 0xc4, 0x2b, 0x48, 0x8a, 0x66, 0x6d, 0xa5, 0xaa, 0x4c, 0x9a, 0x4c,
	0x7a, 0xb3, 0xd1, 0x45, 0x32, 0x5f, 0x78, 0x22, 0x7b, 0x56, 0xc4, 0x3f, 0x10, 0x57, 0xf4, 0x68,
	0x5c, 0xdb, 0xa1, 0xdf, 0xee, 0xe0, 0x12, 0x85, 0x80, 0x3e, 0x36, 0x12, 0x53, 0x60, 0x96, 0xd7,
	0xe2, 0x08, 0x7a, 0x46, 0x62, 0x3a, 0x62, 0xca, 0x2d, 0xa7, 0xbf, 0x3b, 0x10, 0x87, 0xa2, 0x22,
	0x85, 0x78, 0x47, 0xda, 0x48, 0x55, 0x71, 0xba, 0xc3, 0xac, 0x85, 0xe2, 0x13, 0x9c, 0x85, 0x86,
	0xb9, 0xac, 0xa4, 0xcd, 0xf7, 0x63, 0xe8, 0xf2, 0x18, 0x4e, 0x82, 0xba, 0xac, 0xa4, 0xbd, 0x7d,
	0x39, 0x11, 0x3f, 0xd9, 0xfc, 0x79, 0x33, 0x86, 0x98, 0x0f, 0xbd, 0x10, 0x3a, 0x2f, 0x51, 0x5c,
	0xc0, 0xe9, 0x5a, 0x55, 0xf7, 0x72, 0xd3, 0x68, 0x42, 0xae, 0xaf, 0x1a, 0x9b, 0x97, 0x86, 0x13,
	0x1f, 0x67, 0x7f, 0xef, 0xc5, 0x5b, 0xaf, 0x5d, 0x1b, 0x31, 0x85, 0xa4, 0xc0, 0xbc, 0xa9, 0xa4,
	0x35, 0xe9, 0x80, 0x03, 0x8a, 0xe7, 0x0b, 0xbc, 0xab, 0xa4, 0xcd, 0xe2, 0x82, 0x7f, 0x8d, 0xf8,
	0x17, 0x92, 0xd2, 0x6c, 0x72, 0xfb, 0x54, 0x13, 0xc7, 0x3e, 0xce, 0xe2, 0xd2, 0x6c, 0x6e, 0x9f,
	0x6a, 0x9a, 0x22, 0x44, 0xde, 0x2d, 0x26, 0xf0, 0x57, 0x28, 0x94, 0xaf, 0x15, 0x52, 0xf8, 0xf7,
	0xe0, 0x6b, 0x5c, 0x29, 0x24, 0x91, 0x42, 0x7f, 0x25, 0xd1, 0xa4, 0x5d, 0x6e, 0xd3, 0x9f, 0x5f,
	0x4a, 0xcc, 0x98, 0x11, 0xff, 0x43, 0x54, 0x17, 0xba, 0x28, 0x4d, 0xda, 0x63, 0x2d, 0x9a, 0xdf,
	0x38, 0x98, 0x05, 0x76, 0xfa, 0xb3, 0x0b, 0xbd, 0x4b, 0x89, 0xe2, 0x14, 0x22, 0x97, 0x84, 0xc4,
	0x50, 0x7d, 0xb0, 0x92, 0xb8, 0x44, 0x71, 0x02, 0x83, 0x5a, 0xbb, 0xd9, 0xbb, 0x20, 0x3b, 0x99,
	0x07, 0xee, 0xd6, 0xad, 0x24, 0x22, 0x69, 0x7f, 0x1e, 0x9f, 0x19, 0x78, 0x8a, 0xcf, 0xf3, 0x06,
	0x8e, 0x83, 0xa1, 0x3d, 0xb8, 0xc4, 0x70, 0x39, 0x0f, 0xbc, 0xe0, 0xff, 0xda, 0x12, 0xc5, 0x3b,
	0xf7, 0x2e, 0x7e, 0x34, 0x64, 0x5e, 0x8e, 0x6d, 0xc0, 0x63, 0x3b, 0x0a, 0xc2, 0x7e, 0x64, 0xef,
	0x41, 0x68, 0x32, 0xb5, 0xaa, 0x0c, 0xbd, 0x70, 0x47, 0xec, 0x3e, 0x6e, 0x95, 0xbd, 0xfd, 0x1c,
	0x46, 0xc6, 0x16, 0xb6, 0x31, 0xfe, 0x9c, 0x31, 0x07, 0x0c, 0x9e, 0xe2, 0x73, 0xbe, 0x86, 0x64,
	0xad, 0xa9, 0xb0, 0x72, 0x47, 0x69, 0x32, 0xe9, 0xcc, 0x46, 0x17, 0xc3, 0xf9, 0x55, 0x20, 0xb2,
	0x67, 0xc9, 0x3d, 0x01, 0xa3, 0x1a, 0xbd, 0xa6, 0xf6, 0x0e, 0x7b, 0x34, 0x55, 0x90, 0xb4, 0x6e,
	0xd7, 0xab, 0xf5, 0xef, 0x53, 0x84, 0x96, 0xf2, 0x51, 0x3e, 0x4a, 0xb4, 0x0f, 0x1c, 0xe5, 0x38,
	0xf3, 0xc0, 0x95, 0x7e, 0x20, 0xb9, 0x79, 0xb0, 0x9c, 0xe2, 0x38, 0x0b, 0xc8, 0xb9, 0x57, 0xba,
	0xa8, 0xda, 0xd4, 0x3c, 0x98, 0x7e, 0x80, 0x01, 0x8f, 0xcf, 0xbd, 0x94, 0xef, 0xf4, 0x14, 0xba,
	0xb8, 0xa5, 0xdb, 0xb0, 0x2b, 0xb6, 0x0d, 0x85, 0x6f, 0x8a, 0x07, 0xab, 0x88, 0x3f, 0x57, 0x1f,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x82, 0xc6, 0x7c, 0xea, 0xc4, 0x04, 0x00, 0x00,
}
