// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/prebid/prebid-server/v2/analytics/pubxai/queue (interfaces: WinningBidQueueInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	utils "github.com/prebid/prebid-server/v2/analytics/pubxai/utils"
)

// MockWinningBidQueueInterface is a mock of WinningBidQueueInterface interface.
type MockWinningBidQueueInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWinningBidQueueInterfaceMockRecorder
}

// MockWinningBidQueueInterfaceMockRecorder is the mock recorder for MockWinningBidQueueInterface.
type MockWinningBidQueueInterfaceMockRecorder struct {
	mock *MockWinningBidQueueInterface
}

// NewMockWinningBidQueueInterface creates a new mock instance.
func NewMockWinningBidQueueInterface(ctrl *gomock.Controller) *MockWinningBidQueueInterface {
	mock := &MockWinningBidQueueInterface{ctrl: ctrl}
	mock.recorder = &MockWinningBidQueueInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWinningBidQueueInterface) EXPECT() *MockWinningBidQueueInterfaceMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockWinningBidQueueInterface) Enqueue(arg0 utils.WinningBid) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Enqueue", arg0)
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockWinningBidQueueInterfaceMockRecorder) Enqueue(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockWinningBidQueueInterface)(nil).Enqueue), arg0)
}

// UpdateConfig mocks base method.
func (m *MockWinningBidQueueInterface) UpdateConfig(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateConfig", arg0, arg1)
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockWinningBidQueueInterfaceMockRecorder) UpdateConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockWinningBidQueueInterface)(nil).UpdateConfig), arg0, arg1)
}
