metadata:
  name: prebid-global
  servicename: prebid-global
  prefix: prebid-global
  labels:
    app.kubernetes.io/name: prebid-global
environment:
  environment: production
annotations:
  alb:
    loadBalancerName: prebid-global
versionSuffix:
  us-west-2: -v2
  us-east-1: -v2
host:
  us-west-2: prebid-global-west-java.production.adthrive.com
  us-east-1: prebid-global-east-java.production.adthrive.com
spec:
  minReplicas: 3
  env:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: SERVER_HTTP_SERVER_INSTANCES
      value: "15"
    - name: SERVER_IDLE_TIMEOUT
      value: "30"
    - name: EXTERNAL_URL
      value: "https://prebid.production.adthrive.com"
    - name: ADMIN_ENDPOINTS_LOGGING_HTTPINTERACTION_ENABLED
      value: "true"
    - name: ADMIN_ENDPOINTS_LOGGING_HTTPINTERACTION_PROTECTED
      value: "false"
    - name: ADMIN_ENDPOINTS_LOGGING_CHANGELEVEL_ENABLED
      value: "true"
    - name: ADMIN_ENDPOINTS_LOGGING_CHANGELEVEL_PROTECTED
      value: "false"
    - name: ADMIN_ENDPOINTS_TRACELOG_ENABLED
      value: "true"
    - name: ADMIN_ENDPOINTS_TRACELOG_PROTECTED
      value: "false"