apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.metadata.prefix }}{{ .Values.metadata.suffix }}{{ .Values.metadata.regionSuffix }}
  labels:
    environment: {{ .Values.metadata.environment }}
    owner: adcode-delivery
    provisioner: helm
    region: {{ .Values.metadata.region }}
    service: prebid-server-java
spec:
  minAvailable: {{ .Values.spec.minReplicas }}
  selector:
    matchLabels: {{.Values.metadata.labels | toYaml | nindent 6}}{{ .Values.metadata.suffix }}{{ .Values.metadata.regionSuffix }}