---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.prefix }}{{ .Values.metadata.name }}{{ .Values.metadata.suffix }}{{ .Values.metadata.regionSuffix }}
  labels:
    environment: {{ .Values.metadata.environment }}
    owner: adcode-delivery
    provisioner: helm
    region: {{ .Values.metadata.region }}
    service: {{ .Values.metadata.name }}
spec:
  ports:
    - port: {{.Values.image.serviceport}}
      targetPort: {{.Values.image.containerport}}
      protocol: TCP
  type: NodePort
  selector: {{ .Values.metadata.labels | toYaml | nindent 4}}{{ .Values.metadata.suffix }}{{ .Values.metadata.regionSuffix }}
