name: Build and Release

on:
  workflow_dispatch:

jobs:
  create-and-push-docker-image:
    name: Publish docker image
    needs: build-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Prebid Server
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest tag
        id: get_latest_tag
        run: |
          sha=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Build image
        run: |
          docker build -t docker.io/prebid/prebid-server:test .