name: Build and Release

on:
  workflow_dispatch:

jobs:
  build-main:
    name: Build main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Build Prebid Server
        run: go build .

  create-docker-image:
    name: Publish docker image
    needs: build-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Prebid Server
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build image
        run: |
          docker build -t docker.io/prebid/prebid-server:test .