name: Adapter Semgrep Check

on:
  pull_request:
    paths: ["adapters/*/*.go"]

permissions:
  contents: read
  pull-requests: read

jobs:
  semgrep-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate Code Diff
        id: calculate_diff
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const utils = require('./.github/workflows/helpers/pull-request-utils.js')
            // consider only non-test Go files that are part of the adapter code
            function fileNameFilter(filename) {
              return filename.startsWith("adapters/") && filename.split("/").length > 2 && filename.endsWith(".go") && !filename.endsWith("_test.go")
            }
            const helper = utils.diffHelper({github, context, fileNameFilter, event: "${{github.event.action}}", testName: "${{github.job}}"})
            return await helper.buildDiff()

      - name: Check For Changes
        id: should_run_semgrep
        run: |
          hasChanges=$(echo '${{ steps.calculate_diff.outputs.result }}' | jq .pullRequest.hasChanges)
          echo "hasChanges=${hasChanges}" >> $GITHUB_OUTPUT

      - name: Install semgrep
        if: contains(steps.should_run_semgrep.outputs.hasChanges, 'true')
        run: |
          pip3 install semgrep==1.22.0
          semgrep --version

      - name: Run Semgrep
        id: run_semgrep_tests
        if: contains(steps.should_run_semgrep.outputs.hasChanges, 'true')
        run: |
          unqouted_string=$(echo '${{ steps.calculate_diff.outputs.result }}' | jq .pullRequest.files | tr -d '"')
          outputs=$(semgrep --gitlab-sast --config=.semgrep/adapter $unqouted_string  | jq '[.vulnerabilities[] | {"file": .location.file, "severity": .severity, "start": .location.start_line, "end": .location.end_line, "message": (.message | gsub("\\n"; "\n"))}]' | jq -c)
          echo "${outputs}" > semgrep_result.json

      - name: Prepare Artifacts
        if: contains(steps.should_run_semgrep.outputs.hasChanges, 'true')
        run: |
          mkdir -p ./semgrep-artifacts/pr-metadata
          cp semgrep_result.json ./semgrep-artifacts/semgrep_result.json
          echo '${{ steps.calculate_diff.outputs.result }}' > ./semgrep-artifacts/diff.json
          echo '${{ github.event.pull_request.number }}' > ./semgrep-artifacts/pr-metadata/pr_number
          echo '${{ github.event.pull_request.head.sha }}' > ./semgrep-artifacts/pr-metadata/head_sha
          echo '${{ github.event.action }}' > ./semgrep-artifacts/pr-metadata/event

      - name: Upload Semgrep Artifacts
        if: contains(steps.should_run_semgrep.outputs.hasChanges, 'true')
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: ./semgrep-artifacts
          retention-days: 1
