on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created
name: Validate
jobs:
  Go:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Validate
      run: |
        ./validate.sh --nofmt --cov --race 10
      env:
        GO111MODULE: "on"
