name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        # Resolves to empty string for push events and falls back to HEAD.
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Validate
      run: |
        ./validate.sh --nofmt --cov --race 10
      env:
        GO111MODULE: "on"
